// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/trpc/:trpc": {
    params: {
      "trpc": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/trpc/:trpc";
  };
  "routes/api.trpc.$trpc.ts": {
    id: "routes/api.trpc.$trpc";
    page: "/api/trpc/:trpc";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};