version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: looney-api-server
    image: looney-api-server:latest
    ports:
      - "5555:5555"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}

  cloud:
    build:
      context: .
      dockerfile: Dockerfile
      target: looney-cloud
    image: looney-cloud:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  sing:
    build:
      context: .
      dockerfile: Dockerfile
      target: looney-sing
    image: looney-sing:latest
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production