volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

services:
  api-server:
    build:
      context: .
      dockerfile: apps/api-server/Dockerfile
    image: looney-api-server:latest
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      API_CORS_ORIGIN: ${DOCKER_API_CORS_ORIGIN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      VIRTUAL_HOST: ${HOST_API_SERVER}
      LETSENCRYPT_HOST: ${HOST_API_SERVER}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cloud:
    build:
      context: .
      dockerfile: apps/cloud/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    image: looney-cloud:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      VIRTUAL_HOST: ${HOST_CLOUD}
      LETSENCRYPT_HOST: ${HOST_CLOUD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sing:
    build:
      context: .
      dockerfile: apps/sing/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    image: looney-sing:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      VIRTUAL_HOST: ${HOST_SING}
      LETSENCRYPT_HOST: ${HOST_SING}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tool:
    build:
      context: .
      dockerfile: apps/tool/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    image: looney-tool:latest
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      VIRTUAL_HOST: ${HOST_TOOL}
      LETSENCRYPT_HOST: ${HOST_TOOL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    image: looney-website:latest
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      VIRTUAL_HOST: ${HOST_WEBSITE}
      LETSENCRYPT_HOST: ${HOST_WEBSITE}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  gen:
    image: jwilder/docker-gen:0.9.1
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/templates:/etc/docker-gen/templates:ro
    command: -notify-sighup nginx-proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx
      - gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      DEFAULT_EMAIL: ${SSL_EMAIL}
