packages:
    - 'apps/*'
    - 'packages/*'

catalog:
    '@types/node': ^24.3.0
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
    typescript: ^5.7.3
    eslint: ^8.57.1
    zod: ^4.0.17
    react: ^18.3.1
    react-dom: ^18.3.1
    autoprefixer: ^10.4.20
    postcss: ^8.5.6
    tailwindcss: ^3.4.17
    '@supabase/supabase-js': ^2.48.1
    dotenv: ^17.2.1
    dotenv-cli: ^10.0.0
    '@remix-run/node': ^2
    '@remix-run/react': ^2
    '@remix-run/dev': ^2
    '@vercel/remix': ^2.16.7
    vite: ^5.4.19
    vite-tsconfig-paths: ^4.3.2
    '@trpc/server': ^11.4.4
    '@tanstack/react-query': ^5
