packages:
    - 'apps/*'
    - 'packages/*'

catalog:
    '@types/react': ^18.3.7
    '@types/react-dom': ^18.3.0
    '@types/express': ^4.17.21
    typescript: ^5.1.6
    eslint: ^8
    react: ^18.3.1
