// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/session/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/session/:sessionId/destroy": {
    params: {
      "sessionId": string;
    };
  };
  "/session/:sessionId/close": {
    params: {
      "sessionId": string;
    };
  };
  "/api/trpc/:trpc": {
    params: {
      "trpc": string;
    };
  };
  "/session": {
    params: {};
  };
  "/insights": {
    params: {};
  };
  "/setlists": {
    params: {};
  };
  "/setlists/:setlistId/edit": {
    params: {
      "setlistId": string;
    };
  };
  "/setlists/:setlistId": {
    params: {
      "setlistId": string;
    };
  };
  "/setlists/:setlistId/destroy": {
    params: {
      "setlistId": string;
    };
  };
  "/setlists/create": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/songs": {
    params: {};
  };
  "/songs/:songId/edit": {
    params: {
      "songId": string;
    };
  };
  "/songs/:songId": {
    params: {
      "songId": string;
    };
  };
  "/songs/:songId/destroy": {
    params: {
      "songId": string;
    };
  };
  "/songs/create": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/session/:sessionId" | "/session/:sessionId/destroy" | "/session/:sessionId/close" | "/api/trpc/:trpc" | "/session" | "/insights" | "/setlists" | "/setlists/:setlistId/edit" | "/setlists/:setlistId" | "/setlists/:setlistId/destroy" | "/setlists/create" | "/signout" | "/signin" | "/songs" | "/songs/:songId/edit" | "/songs/:songId" | "/songs/:songId/destroy" | "/songs/create";
  };
  "routes/session.$sessionId.tsx": {
    id: "routes/session.$sessionId";
    page: "/session/:sessionId" | "/session/:sessionId/destroy" | "/session/:sessionId/close";
  };
  "routes/session.$sessionId.destroy.tsx": {
    id: "routes/session.$sessionId.destroy";
    page: "/session/:sessionId/destroy";
  };
  "routes/session.$sessionId.close.tsx": {
    id: "routes/session.$sessionId.close";
    page: "/session/:sessionId/close";
  };
  "routes/api.trpc.$trpc.ts": {
    id: "routes/api.trpc.$trpc";
    page: "/api/trpc/:trpc";
  };
  "routes/session._index.tsx": {
    id: "routes/session._index";
    page: "/session";
  };
  "routes/insights.tsx": {
    id: "routes/insights";
    page: "/insights";
  };
  "routes/setlists.tsx": {
    id: "routes/setlists";
    page: "/setlists" | "/setlists/:setlistId/edit" | "/setlists/:setlistId" | "/setlists/:setlistId/destroy" | "/setlists/create";
  };
  "routes/setlists.$setlistId_.edit.tsx": {
    id: "routes/setlists.$setlistId_.edit";
    page: "/setlists/:setlistId/edit";
  };
  "routes/setlists.$setlistId.tsx": {
    id: "routes/setlists.$setlistId";
    page: "/setlists/:setlistId" | "/setlists/:setlistId/destroy";
  };
  "routes/setlists.$setlistId.destroy.tsx": {
    id: "routes/setlists.$setlistId.destroy";
    page: "/setlists/:setlistId/destroy";
  };
  "routes/setlists._index.tsx": {
    id: "routes/setlists._index";
    page: "/setlists";
  };
  "routes/setlists.create.tsx": {
    id: "routes/setlists.create";
    page: "/setlists/create";
  };
  "routes/signout.tsx": {
    id: "routes/signout";
    page: "/signout";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/songs.tsx": {
    id: "routes/songs";
    page: "/songs" | "/songs/:songId/edit" | "/songs/:songId" | "/songs/:songId/destroy" | "/songs/create";
  };
  "routes/songs.$songId_.edit.tsx": {
    id: "routes/songs.$songId_.edit";
    page: "/songs/:songId/edit";
  };
  "routes/songs.$songId.tsx": {
    id: "routes/songs.$songId";
    page: "/songs/:songId" | "/songs/:songId/destroy";
  };
  "routes/songs.$songId.destroy.tsx": {
    id: "routes/songs.$songId.destroy";
    page: "/songs/:songId/destroy";
  };
  "routes/songs._index.tsx": {
    id: "routes/songs._index";
    page: "/songs";
  };
  "routes/songs.create.tsx": {
    id: "routes/songs.create";
    page: "/songs/create";
  };
};