// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create/:guestId/:songId": {
    params: {
      "guestId": string;
      "songId": string;
    };
  };
  "/api/trpc/:trpc": {
    params: {
      "trpc": string;
    };
  };
  "/start/:resetId": {
    params: {
      "resetId": string;
    };
  };
  "/:guestId?": {
    params: {
      "guestId"?: string;
    };
  };
  "/:guestId?/feedback": {
    params: {
      "guestId"?: string;
    };
  };
  "/:guestId?/songs": {
    params: {
      "guestId"?: string;
    };
  };
  "/:guestId?/tip": {
    params: {
      "guestId"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create/:guestId/:songId" | "/api/trpc/:trpc" | "/start/:resetId" | "/:guestId?" | "/:guestId?/feedback" | "/:guestId?/songs" | "/:guestId?/tip";
  };
  "routes/create.$guestId.$songId.tsx": {
    id: "routes/create.$guestId.$songId";
    page: "/create/:guestId/:songId";
  };
  "routes/api.trpc.$trpc.ts": {
    id: "routes/api.trpc.$trpc";
    page: "/api/trpc/:trpc";
  };
  "routes/start.$resetId.tsx": {
    id: "routes/start.$resetId";
    page: "/start/:resetId";
  };
  "routes/($guestId).tsx": {
    id: "routes/($guestId)";
    page: "/:guestId?" | "/:guestId?/feedback" | "/:guestId?/songs" | "/:guestId?/tip";
  };
  "routes/($guestId).feedback.tsx": {
    id: "routes/($guestId).feedback";
    page: "/:guestId?/feedback";
  };
  "routes/($guestId).songs.tsx": {
    id: "routes/($guestId).songs";
    page: "/:guestId?/songs";
  };
  "routes/($guestId).tip.tsx": {
    id: "routes/($guestId).tip";
    page: "/:guestId?/tip";
  };
};